[package]
name = "regular-ft"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
uint = { version = "=0.9.5", default-features = false }
near-sdk = "=4.1.1"
near-contract-standards = "=4.1.1"
